CREATE DATABASE HR_PROJECT;
USE HR_PROJECT;

CREATE TABLE EMPLOYEES( UNNAMED INT,
EMPLOYEEID VARCHAR(50) PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50),
DEPARTMENT_NAME VARCHAR(50),
JOB_TITLE VARCHAR(100),
HIRE_DATE DATE,
LOCATION VARCHAR(100),
PERFORMANCE_RATING INT,
EXPERIENCE INT,
EMPLOYEE_STATUS VARCHAR(50),
WORK_MODE VARCHAR(50),
SALARY INT);
 LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\HR_Data_MNC_Data Science Lovers.csv'
INTO TABLE EMPLOYEES
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
UNNAMED,
EMPLOYEEID ,
EMPLOYEE_NAME ,
DEPARTMENT_NAME,
JOB_TITLE,
@HIRE_DATE,
LOCATION ,
PERFORMANCE_RATING,
EXPERIENCE,
EMPLOYEE_STATUS ,
WORK_MODE ,
SALARY
 )
 SET HIRE_DATE = STR_TO_DATE(@HIRE_DATE, '%Y-%m-%d');
 
SELECT*FROM  EMPLOYEES;
ALTER TABLE EMPLOYEES DROP UNNAMED;
ALTER TABLE EMPLOYEES DROP LOCATION;

SELECT distinct(JOB_TITLE) FROM EMPLOYEES;
CREATE TABLE DEPARTMENTS(DEPARTMENT_NAME VARCHAR(50),
DEPARTMENT_ID  INT auto_increment PRIMARY KEY);
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) SELECT distinct(DEPARTMENT_NAME) FROM EMPLOYEES; 
SELECT*FROM DEPARTMENTS;

CREATE TABLE JOB(JOB_TITLE VARCHAR(100),
JOB_ID INT AUTO_INCREMENT PRIMARY KEY);
INSERT INTO JOB (JOB_TITLE) SELECT distinct(JOB_TITLE) FROM EMPLOYEES;
select* from JOB;
